name = "stlc"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Stlc"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.26.0"

[[lean_lib]]
name = "Stlc"
